# Generated by Django 5.1.15 on 2026-09-11 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(db_index=True, help_text='Trigger key that initiated notification', max_length=50)),
                ('channel', models.CharField(db_index=True, help_text='Channel (whatsapp, email, webpush)', max_length=20)),
                ('recipient', models.CharField(help_text='Recipient phone number, email address, or device identifier', max_length=255)),
                ('payload', models.JSONField(default=dict, help_text='Rendered content and metadata sent to provider')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('mock_delivered', 'Mock Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='sent', max_length=30)),
                ('response_details', models.JSONField(default=dict, help_text='Provider API response, error message, or mock reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique programmatic identifier (e.g. login, logout)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable trigger name (e.g. User Login)', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Description of when this trigger fires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this trigger is active and fires notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_data', models.JSONField(default=dict, help_text='OneSignal player_id or browser push subscription dictionary')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is currently valid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Associated authenticated user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web Push Subscription',
                'verbose_name_plural': 'Web Push Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('webpush', 'Web Push')], help_text='Delivery channel', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether notifications for this channel are enabled')),
                ('title', models.CharField(blank=True, default='', help_text='Heading or title (primarily for Web Push)', max_length=255)),
                ('subject', models.CharField(blank=True, default='', help_text='Subject line (primarily for Email)', max_length=255)),
                ('body', models.TextField(help_text='Template body supporting {{variable}} placeholders')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('synced', 'Synced'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Template sync or review status (used for WhatsApp Meta Cloud approval)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(help_text='Associated trigger event', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.trigger')),
            ],
            options={
                'verbose_name': 'Channel Template',
                'verbose_name_plural': 'Channel Templates',
                'ordering': ['trigger', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('trigger', 'channel'), name='unique_trigger_channel')],
            },
        ),
    ]
